export const REQUEST_ALL_PRODUCTS = "REQUEST_ALL_PRODUCTS";
export const SUCCESS_ALL_PRODUCTS = "SUCCESS_ALL_PRODUCTS";
export const FAIL_ALL_PRODUCTS = "FAIL_ALL_PRODUCTS";

export const REQUEST_SINGLE_PRODUCT = "REQUEST_SINGLE_PRODUCT";
export const SUCCESS_SINGLE_PRODUCT = "SUCCESS_SINGLE_PRODUCT";
export const FAIL_SINGLE_PRODUCT = "FAIL_SINGLE_PRODUCT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";